version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11
    working_directory: ~/project

jobs:
  ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Nightwatch UI Tests
          command: |
            # تأكد إن ملف الـ config موجود
            if [ ! -f AutomationTask/UI_Task/nightwatch.conf.js ]; then
              echo "❌ Nightwatch config file not found!"
              exit 1
            fi

            # شغل الاختبارات من المسار الصحيح
            npx nightwatch --config AutomationTask/UI_Task/nightwatch.conf.js "AutomationTask/UI_Task/**/test/*.js"

  api-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run API Tests
          command: |
            npx playwright test --config=AutomationTask/API_Task/playwright.config.js

workflows:
  version: 2
  test_all:
    jobs:
      - ui-tests
      - api-tests
