version: 2.1

executors:
  node-chrome:
    docker:
      - image: cimg/node:18.17-browsers
    working_directory: ~/repo

jobs:
  ui-tests:
    executor: node-chrome
    steps:
      - checkout

      - run:
          name: Check Chrome installation
          command: |
            google-chrome --version || echo "google-chrome not found"
            google-chrome-stable --version || echo "google-chrome-stable not found"
            which google-chrome || echo "google-chrome binary not found"
            which google-chrome-stable || echo "google-chrome-stable binary not found"

      - run:
          name: Install Google Chrome if missing
          command: |
            if ! command -v google-chrome > /dev/null && ! command -v google-chrome-stable > /dev/null; then
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            else
              echo "Chrome already installed"
            fi

      - run:
          name: Install chromedriver
          command: npm install chromedriver --save-dev

      - run:
          name: Install dependencies for all UI tasks
          command: |
            cd AutomationTask/UI_Task/Task1 && npm install
            cd ../Task2 && npm install
            cd ../Task3 && npm install

      - run:
          name: Run UI Task 1
          command: |
            cd AutomationTask/UI_Task/Task1
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/homeTest.js


  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd AutomationTask/API_Task
            npm install
      - run:
          name: Run API tests
          command: |
            cd AutomationTask/API_Task
            npm test

workflows:
  version: 2
  ui-then-api:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
          filters:
            branches:
              only: main
