version: 2.1

executors:
  node-chrome:
    docker:
      - image: cimg/node:18.17-browsers
    working_directory: ~/repo

jobs:
  ui-tests:
    executor: node-chrome
    steps:
      - checkout
      - run:
          name: Install dependencies for all UI tasks
          command: |
            cd AutomationTask/UI_Task/Task1 && npm install
            cd ../Task2 && npm install
            cd ../Task3 && npm install
      - run:
          name: Run UI Task 1
          command: |
            cd AutomationTask/UI_Task/Task1
            npx nightwatch test/homeTest.js
      - run:
          name: Run UI Task 2
          command: |
            cd AutomationTask/UI_Task/Task2
            npx nightwatch test/registrationTest.js
      - run:
          name: Run UI Task 3
          command: |
            cd AutomationTask/UI_Task/Task3
            npx nightwatch test/searchDressTest.js

  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd AutomationTask/API_Task
            npm install
      - run:
          name: Run API tests
          command: |
            cd AutomationTask/API_Task
            npm test

workflows:
  version: 2
  ui-then-api:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
          filters:
            branches:
              only: main
