version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install all UI dependencies
          command: |
            cd AutomationTask/UI_Task/Task1 && npm install
            cd ../Task2 && npm install
            cd ../Task3 && npm install
      - run:
          name: Run all UI Nightwatch tests
          command: npx nightwatch AutomationTask/UI_Task/**/test/*.js

  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install API dependencies
          command: |
            cd AutomationTask/API_Task
            npm install
      - run:
          name: Run all API tests
          command: npx jest AutomationTask/API_Task/tests/*.js

workflows:
  version: 2
  test-all:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
