version: 2.1

executors:
  node-chrome:
    docker:
      - image: cimg/node:18.17-browsers
    working_directory: /home/circleci/repo 

  node:
    docker:
      - image: cimg/node:18.17
    working_directory: /home/circleci/repo

jobs:

  install-ui-dependencies:
    executor: node-chrome
    steps:
      - checkout:
          path: ~/repo 
      - run:
          name: Install Google Chrome Stable
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Install chromedriver
          command: npm install chromedriver --save-dev
      - run:
          name: Install dependencies for all UI tasks
          command: |
            cd AutomationTask/UI_Task/Task1 && npm install
            cd ../Task2 && npm install
            cd ../Task3 && npm install
      - persist_to_workspace:
          root: .
          paths:
            - AutomationTask

  ui-test-1:
    executor: node-chrome
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run UI Task 1
          command: |
            cd AutomationTask/UI_Task/Task1
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/homeTest.js
            
  ui-test-2:
    executor: node-chrome
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run UI Task 2
          command: |
            cd AutomationTask/UI_Task/Task2
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/registrationTest.js
            
  ui-test-3:
    executor: node-chrome
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run UI Task 3
          command: |
            cd AutomationTask/UI_Task/Task3
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/searchDressTest.js

  api-tests:
    executor: node
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install server dependencies
          command: |
            cd AutomationTask/mock-user-auth && npm install
      - run:
          name: Install API dependencies
          command: |
            cd AutomationTask/API_Task && npm install
      - run:
          name: Run Server
          command: |
            cd AutomationTask/mock-user-auth
            nohup npm run dev > server.log 2>&1 &
            echo "Waiting for server to be ready on port 3000..."
            for i in {1..30}; do
              nc -z localhost 3000 && break
              echo "Waiting..."
              sleep 2
            done
      - run:
          name: Run API tests
          command: |
            cd AutomationTask/API_Task
            chmod +x node_modules/.bin/jest
            npm test

workflows:
  version: 2
  ui-tests-pipeline:
    jobs:
      - install-ui-dependencies
      - ui-test-1:
          requires:
            - install-ui-dependencies
      - ui-test-2:
          requires:
            - install-ui-dependencies
      - ui-test-3:
          requires:
            - install-ui-dependencies

  api-tests-pipeline:
    jobs:
      - api-tests