version: 2.1

executors:
  node-chrome:
    docker:
      - image: cimg/node:18.17-browsers
    working_directory: ~/repo

jobs:
  ui-tests:
    executor: node-chrome
    steps:
      - checkout

      - run:
          name: Install Google Chrome Stable
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable


      - run:
          name: Install chromedriver
          command: npm install chromedriver --save-dev

      - run:
          name: Install dependencies for all UI tasks
          command: |
            cd AutomationTask/UI_Task/Task1 && npm install
            cd ../Task2 && npm install
            cd ../Task3 && npm install

      - run:
          name: Run UI Task 1
          command: |
            cd AutomationTask/UI_Task/Task1
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/homeTest.js

      - run:
          name: Run UI Task 2
          command: |
            cd AutomationTask/UI_Task/Task2
            chmod +x node_modules/.bin/nightwatch
            npx nightwatch test/registrationTest.js

      # - run:
      #     name: Run UI Task 3
      #     command: |
      #       cd AutomationTask/UI_Task/Task3
      #       chmod +x node_modules/.bin/nightwatch
      #       npx nightwatch test/searchDressTest.js


  api-tests:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install server dependencies
          command: |
            cd AutomationTask/mock-user-auth && npm install

      - run:
          name: Install API dependencies
          command: |
            cd AutomationTask/API_Task
            npm install

      - run:
          name: Run Server
          command: |
            cd AutomationTask/mock-user-auth
            npm run dev

      - run:
          name: Run API tests
          command: |
            cd AutomationTask/API_Task
            npm test

workflows:
  version: 2
  ui-then-api:
    jobs:
      - ui-tests
      - api-tests:
          requires:
            - ui-tests
          filters:
            branches:
              only: main
